spring.application.name=event-gateway-service
server.port=8080

spring.datasource.url=jdbc:h2:mem:gatewaydb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true

account.service.base-url=http://localhost:8081

account.service.timeout-ms=2000
account.client.max-attempts=2
account.client.backoff-ms=200
